baseURL = "http://maru10t.github.io/"
languageCode = "ja"
title = "Takafumi Maruishi"
contentDir="content"
disableKinds = ["RSS", "sitemap"]
theme = "hugo-xmin"
publishDir = "docs"
[taxonomies]
tag = "tags"
